Raw Dataset showing how Ohio counties voted in 2016 and 2020

In [1]:
import pandas as pd

In [30]:
df.head(10)

,County,Margin,2016 margin,Est. votes reported,Unnamed: 4,Total votes,Absentee
0,Franklin,Biden +31,D+25.8,100%,NaN,"630,577",—
1,Cuyahoga,Biden +34,D+35.2,100%,NaN,"625,670","584,988"
2,Hamilton,Biden +16,D+10.3,100%,NaN,"430,929","245,471"
3,Summit,Biden +10,D+8.5,100%,NaN,"280,473","149,069"
4,Montgomery,Biden +2,R+0.7,100%,NaN,"268,505","154,486"
5,Lucas,Biden +17,D+17.7,100%,NaN,"200,623",—
6,Stark,Trump +19,R+17.2,100%,NaN,"189,879",—
7,Butler,Trump +24,R+27.6,100%,NaN,"186,737",—
8,Lorain,Trump +2,D+0.1,100%,NaN,"157,437",—
9,Warren,Trump +31,R+37.1,100%,NaN,"136,100","88,884"

In [36]:
df = pd.read_csv("Countyvotesraw.csv")
df.tail(10)

,County,Margin,2016 margin,Est. votes reported,Unnamed: 4,Total votes,Absentee
78,Pike,Trump +49,R+36.5,100%,NaN,"12,412",—
79,Adams,Trump +64,R+55.5,100%,NaN,"12,145",—
80,Wyandot,Trump +50,R+46.6,100%,NaN,"11,390",—
81,Meigs,Trump +53,R+50.3,100%,NaN,"10,951","6,386"
82,Paulding,Trump +51,R+48.5,100%,NaN,"9,467","5,735"
83,Harrison,Trump +53,R+48,100%,NaN,"7,655",—
84,Monroe,Trump +54,R+46.8,100%,NaN,"7,148",—
85,Morgan,Trump +48,R+41.6,100%,NaN,"6,847",—
86,Noble,Trump +63,R+55.1,100%,NaN,"6,343",—
87,Vinton,Trump +55,R+45.7,100%,NaN,"6,030",—

https://docs.google.com/spreadsheets/d/17Zu-_KbkyiVTJcO1kp5rcvnh33GElxEIeyet80fvxLQ/edit#gid=0

In [39]:
df.shape

(88, 7)

https://docs.google.com/spreadsheets/d/1iSYR9FXFGz9-97fKEkhA4aUARrnmODSI5dli6PlXM3Q/edit#gid=0

In [32]:
df = pd.read_csv("Countyvotestidied.csv")
df.head(10)

     Cuyahoga   Biden +34  D+35.2 Est. votes reported Total votes Absentee
0      Summit   Biden +10   D+8.5                100%     625,670  584,988
1  Montgomery    Biden +2   R+0.7                100%     430,929  245,471
2       Lucas   Biden +17  D+17.7                100%     280,473  149,069
3       Stark   Trump +19  R+17.2                100%     268,505  154,486
4      Butler   Trump +24  R+27.6                100%     200,623        0
5      Lorain    Trump +2   D+0.1                100%     189,879   88,884
6      Warren   Trump +31  R+37.1                100%     186,737   82,258
7        Lake   Trump +14  R+15.2                100%     157,437        0
8    Delaware    Trump +7  R+15.8                100%     136,100   67,800
9    Mahoning  Trump +1.9   D+3.2                100%     130,509        0

In [41]:
df = pd.read_csv("Countyvotestidied.csv")
df.tail(10)

    Cuyahoga  Biden +34  D+35.2 Est. votes reported Total votes Absentee
75      Pike  Trump +49  R+36.5                100%      12,947        0
76     Adams  Trump +64  R+55.5                100%      12,612        0
77   Wyandot  Trump +50  R+46.6                100%      12,412    6,386
78     Meigs  Trump +53  R+50.3                100%      12,145    5,735
79  Paulding  Trump +51  R+48.5                100%      11,390        0
80  Harrison  Trump +53    R+48                100%      10,951        0
81    Monroe  Trump +54  R+46.8                100%       9,467        0
82    Morgan  Trump +48  R+41.6                100%       7,655        0
83     Noble  Trump +63  R+55.1                100%       7,148        0
84    Vinton  Trump +55  R+45.7                100%       6,847        0

Raw dataset on how young Black Americans view the presidental candidates

In [42]:
df = pd.read_csv("Howvotersthinkraw.csv")
df.head(10)

                             Views on the candidates Unnamed: 1
0      Have anything positive to say about Joe Biden        NaN
1                                                NaN        46%
2  Plan to vote for Joe Biden in the general elec...        NaN
3                                                47%        47%
4   Have anything positive to say about Donald Trump        NaN
5                                                 5%         5%
6  Plan to vote for Donald Trump in the general e...        NaN
7                                                 8%         8%
8                                       Voting plans        NaN
9  Trust their state to report their vote accurately        NaN

https://docs.google.com/spreadsheets/d/1RTSPmV6z0I5pF2t4KZs6WDYn4piMdMhFyVJ9k55n4us/edit#gid=0

In [43]:
df = pd.read_csv("Howvotersthinkraw.csv")
df.tail(10)

                              Views on the candidates Unnamed: 1
20  Say the Republican Party is welcoming to Black...        NaN
21                                                28%        28%
22  View the Democratic Party as more welcoming th...        NaN
23                                                51%        51%
24  Trust Democrats in Congress to do what's best ...        NaN
25                                                44%        44%
26  Trust Republicans in Congress to do what's bes...        NaN
27                                                29%        29%
28  Trust Democrats more than Republicans to do wh...        NaN
29                                                48%        48%

In [44]:
df.shape

(30, 2)

In [46]:
df = pd.read_csv("Howvotersthinktidied.csv")
df.head(10)

                             Views on the candidates
0      Have anything positive to say about Joe Biden
1                                                46%
2  Plan to vote for Joe Biden in the general elec...
3                                                47%
4   Have anything positive to say about Donald Trump
5                                                 5%
6  Plan to vote for Donald Trump in the general e...
7                                                 8%
8                                       Voting plans
9  Trust their state to report their vote accurately

In [47]:
df = pd.read_csv("Howvotersthinktidied.csv")
df.tail(10)

                              Views on the candidates
20  Say the Republican Party is welcoming to Black...
21                                                28%
22  View the Democratic Party as more welcoming th...
23                                                51%
24  Trust Democrats in Congress to do what's best ...
25                                                44%
26  Trust Republicans in Congress to do what's bes...
27                                                29%
28  Trust Democrats more than Republicans to do wh...
29                                                48%

In [48]:
df.shape

(30, 1)

https://docs.google.com/spreadsheets/d/1RTSPmV6z0I5pF2t4KZs6WDYn4piMdMhFyVJ9k55n4us/edit#gid=0